version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    labels:
      collectd_docker_app: "monitoring"
      collectd_docker_task: "elasticsearch"
    mem_limit: 1000000000
  kibana:
    image: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    labels:
      collectd_docker_app: "monitoring"
      collectd_docker_task: "kibana"
    mem_limit: 1000000000
