version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "9001:9001"
    labels:
      collectd_docker_app: "application"
      collectd_docker_task: "proxy"
    mem_limit: 100000000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/tmp/logs:/var/tmp/logs
